# Generated by Django 4.0.2 on 2022-02-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedentity',
            old_name='tag',
            new_name='tag1',
        ),
    ]
